services:

  db-orders:
    image: postgres:16-alpine
    container_name: db-orders
    environment:
      - POSTGRES_DB=orders_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d orders_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - orders_data:/var/lib/postgresql/data

  db-notifications:
    image: postgres:16-alpine
    container_name: db-notifications
    environment:
      - POSTGRES_DB=notifications_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d notifications_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    volumes:
      - notifications_data:/var/lib/postgresql/data

  db-deliveries:
    image: postgres:16-alpine
    container_name: db-deliveries
    environment:
      - POSTGRES_DB=deliveries_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d deliveries_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5435:5432"
    volumes:
      - deliveries_data:/var/lib/postgresql/data

  db-payments:
    image: postgres:16-alpine
    container_name: db-payments
    environment:
      - POSTGRES_DB=payments_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d payments_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5436:5432"
    volumes:
      - payments_data:/var/lib/postgresql/data

  db-users:
    image: postgres:16-alpine
    container_name: db-users
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d users_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5437:5432"
    volumes:
      - users_data:/var/lib/postgresql/data

  db-products:
    image: postgres:16-alpine
    container_name: db-products
    environment:
      - POSTGRES_DB=products_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d products_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5438:5432"
    volumes:
      - products_data:/var/lib/postgresql/data

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: e-commerce/order-service:1.0
    container_name: order-service
    depends_on:
      db-orders:
        condition: service_healthy
    # ports:
    #  - "8081:8080"
    environment:
      - SPRING_DATASOURCE_HOST=db-orders
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-orders:5432/orders_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_RABBITMQ_ADDRESSES=${SPRING_RABBITMQ_ADDRESSES}
      - PRODUCT_SERVICE_URL=http://product-service:8080

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    image: e-commerce/notification-service:1.0
    container_name: notification-service
    depends_on:
      db-notifications:
        condition: service_healthy
    # ports:
    #  - "8082:8080"
    environment:
      - SPRING_DATASOURCE_HOST=db-notifications
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-notifications:5432/notifications_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_RABBITMQ_ADDRESSES=${SPRING_RABBITMQ_ADDRESSES}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}

  deliveries-service:
    build:
      context: ./delivery-service
      dockerfile: Dockerfile
    image: e-commerce/deliveries-service:1.0
    container_name: deliveries-service
    depends_on:
      db-deliveries:
        condition: service_healthy
    # ports:
    #  - "8083:8080"
    environment:
      - SPRING_DATASOURCE_HOST=db-deliveries
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-deliveries:5432/deliveries_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_RABBITMQ_ADDRESSES=${SPRING_RABBITMQ_ADDRESSES}

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    image: e-commerce/payment-service:1.0
    container_name: payment-service
    depends_on:
      db-payments:
        condition: service_healthy
    # ports:
    #  - "8084:8080"
    environment:
      - SPRING_DATASOURCE_HOST=db-payments
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-payments:5432/payments_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_RABBITMQ_ADDRESSES=${SPRING_RABBITMQ_ADDRESSES}
      - MERCADOPAGO_ACCESS_TOKEN=${MERCADOPAGO_ACCESS_TOKEN}

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: e-commerce/user-service:1.0
    container_name: user-service
    depends_on:
      db-users:
        condition: service_healthy
    # ports:
    #  - "8085:8080"
    environment:
      - SPRING_DATASOURCE_HOST=db-users
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-users:5432/users_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_RABBITMQ_ADDRESSES=${SPRING_RABBITMQ_ADDRESSES}

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: e-commerce/auth-service:1.0
    container_name: auth-service
    depends_on:
      user-service:
        condition: service_started
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - USER_SERVICE_URL=http://user-service:8080

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: e-commerce/product-service:1.0
    container_name: product-service
    depends_on:
      db-products:
        condition: service_healthy
    # ports:
    #  - "8085:8080"
    environment:
      - SPRING_DATASOURCE_HOST=db-products
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-products:5432/products_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
#      - SPRING_RABBITMQ_ADDRESSES=${SPRING_RABBITMQ_ADDRESSES}

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: e-commerce/api-gateway:1.0
    container_name: api-gateway
    depends_on:
      - order-service
      - deliveries-service
      - payment-service
      - user-service
      - notification-service
      - product-service
      - auth-service
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}

networks:
  default:
    name: ecommerce-network

volumes:
  orders_data:
  notifications_data:
  deliveries_data:
  payments_data:
  users_data:
  products_data: