spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/api/orders, /api/orders/**

        - id: deliveries-service
          uri: http://deliveries-service:8080
          predicates:
            - Path=/api/deliveries/**

        - id: payment-service
          uri: http://payment-service:8080
          predicates:
            - Path=/api/payments/**

        - id: webhook-service
          uri: http://payment-service:8080
          predicates:
            - Path=/webhooks/**

        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/**