INSERT INTO tb_products
(id, name, description, price, stock_quantity, category, product_status, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Console Pulse X', 'Console de alta performance para jogos, streaming e entretenimento em casa.', 2899.90, 12, 'ELECTRONICS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Fone Wave ANC', 'Fone bluetooth com cancelamento de ruido, bateria longa e estojo compacto.', 399.90, 35, 'ELECTRONICS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Smartwatch Core Fit', 'Relogio inteligente com monitoramento de saude, notificacoes e modos de treino.', 549.90, 22, 'ELECTRONICS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Teclado Lumina Pro', 'Teclado mecanico compacto com iluminacao RGB e switches silenciosos.', 329.90, 18, 'ELECTRONICS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
,
    (gen_random_uuid(), 'Jaqueta Urban Fit', 'Jaqueta casual com corte moderno, tecido resistente e acabamento premium.', 349.90, 16, 'CLOTHING', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Camiseta Essential Cotton', 'Camiseta basica em algodao macio para uso diario.', 79.90, 60, 'CLOTHING', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Tenis Street Flow', 'Tenis urbano leve com solado confortavel e visual minimalista.', 259.90, 28, 'CLOTHING', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
,
    (gen_random_uuid(), 'Luminaria Aura', 'Luminaria inteligente com controle de intensidade e temperatura de cor.', 279.90, 24, 'HOME', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Cafeteira Daily Brew', 'Cafeteira compacta para cafe coado com jarra de vidro e filtro reutilizavel.', 189.90, 19, 'HOME', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Organizador Modular', 'Kit organizador modular para escritorio, cozinha ou quarto.', 119.90, 40, 'HOME', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
,
    (gen_random_uuid(), 'Tenis Motion Pro', 'Tenis esportivo com amortecimento responsivo para treinos e caminhadas.', 499.90, 20, 'SPORTS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Garrafa Hydro Max', 'Garrafa termica de alta capacidade para academia, trilhas e rotina diaria.', 89.90, 55, 'SPORTS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Mochila Trail Pack', 'Mochila resistente com compartimentos para esporte, viagem e trabalho.', 219.90, 18, 'SPORTS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
,
    (gen_random_uuid(), 'Arquitetura Limpa', 'Livro tecnico para desenvolvedores sobre organizacao e qualidade de software.', 89.90, 30, 'BOOKS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Mindset de Produto', 'Livro sobre estrategia, descoberta e construcao de produtos digitais.', 74.90, 26, 'BOOKS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Historias Para Dormir', 'Coletanea de contos leves para leitura noturna.', 49.90, 34, 'BOOKS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
,
    (gen_random_uuid(), 'Kit Glow Daily', 'Kit de cuidados faciais com textura leve para rotina diaria.', 159.90, 32, 'BEAUTY', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Perfume Citrus Noir', 'Perfume com notas citricas, amadeiradas e fixacao prolongada.', 229.90, 14, 'BEAUTY', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Secador Air Shine', 'Secador de cabelo potente com controle de temperatura e acabamento brilhante.', 299.90, 11, 'BEAUTY', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
,
    (gen_random_uuid(), 'Cafe Especial Serra', 'Cafe torrado em graos com notas de chocolate e caramelo.', 42.90, 80, 'FOOD', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Chocolate Dark 70', 'Chocolate meio amargo com 70 por cento de cacau.', 24.90, 75, 'FOOD', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Azeite Reserva', 'Azeite extra virgem selecionado para preparos especiais.', 59.90, 38, 'FOOD', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
,
    (gen_random_uuid(), 'Blocos Creative Box', 'Conjunto de blocos coloridos para criacao e brincadeiras educativas.', 129.90, 25, 'TOYS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Robo Mini Explorer', 'Brinquedo interativo com movimentos programaveis e sons divertidos.', 199.90, 17, 'TOYS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Quebra-Cabeca Mundo', 'Quebra-cabeca ilustrado com mapa mundial e 500 pecas.', 69.90, 29, 'TOYS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
,
    (gen_random_uuid(), 'Suporte Veicular Mag', 'Suporte magnetico para smartphone com fixacao em painel automotivo.', 49.90, 45, 'AUTOMOTIVE', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Aspirador Auto Clean', 'Aspirador portatil para limpeza interna de veiculos.', 149.90, 21, 'AUTOMOTIVE', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Kit Emergencia Road', 'Kit automotivo com itens essenciais para seguranca em viagens.', 179.90, 13, 'AUTOMOTIVE', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
,
    (gen_random_uuid(), 'Monitor Cardio Band', 'Faixa monitoradora de batimentos para treinos e acompanhamento fisico.', 189.90, 20, 'HEALTH', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (gen_random_uuid(), 'Umidificador Fresh Air', 'Umidificador compacto com operacao silenciosa para ambientes internos.', 139.90, 27, 'HEALTH', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);